"""Traductions de l'interface utilisateur en espagnol."""

TRADUCTIONS: dict[str, str] = {
    # General
    "app_titre": "Gestion de recursos",
    "recherche_globale": "Buscar en todos los recursos...",
    "recherche": "Buscar",
    "filtros": "Filtros",
    "legende_statuts": "Leyenda de estados",
    "legende_statut_info": "En taller (ver detalle)",
    "installer_pwa_titre": "Instalar la aplicacion",
    "installer_pwa_ios": "En Safari: Compartir, luego Anadir a pantalla de inicio.",
    "installer_pwa_android": "Anada esta pagina a la pantalla de inicio para un acceso rapido.",
    "installer_pwa_bouton": "Instalar",
    "installer_pwa_fermer": "Ahora no",
    "recherche_placeholder": "Matricula, modelo, usuario...",
    "aucun_resultat": "No se encontraron resultados",
    "proximamente": "Proximamente",
    "types_materiel": "Tipos de material",
    "tableau_bord": "Panel de control",
    "bienvenue_accueil": "Gestion del parque de recursos corporativo",
    "alertes_attention": "elemento(s) requieren atencion",
    "stat_total": "Total",
    "stat_disponibles": "Disponibles",
    "stat_en_service": "En servicio",
    "stat_indisponible": "No disponible",
    "accueil": "Inicio",
    "nav_mobile": "Navegacion principal",
    "enregistrer": "Guardar",
    "annuler": "Cancelar",
    "actions": "Acciones",
    "fermer": "Cerrar",
    "retour_liste": "Volver a la lista",
    "retour_accueil": "Volver al inicio",
    # Statuts
    "statut": "Estado",
    "statut_libre": "Libre",
    "statut_occupe": "Ocupado",
    "statut_disponible": "Disponible",
    "statut_au_garage": "En taller",
    "statut_no_disponible": "No disponible",
    "tous": "Todos",
    # ITV
    "itv": "ITV",
    "itv_valide": "Valida",
    "itv_expire_bientot": "Proxima a vencer",
    "itv_expiree": "Vencida",
    "itv_hasta_el": "hasta el",
    "itv_desde_el": "desde el",
    "date_expiration_itv": "Fecha de vencimiento ITV",
    "modifier_itv": "Modificar ITV",
    "itv_etat_actuel": "Estado actual",
    "itv_modifiee": "ITV actualizada correctamente",
    "erreur_itv": "Error al actualizar la ITV",
    "erreur_itv_expiree": "No se puede usar un vehiculo con ITV vencida",
    "filtre_itv_valide": "ITV valida",
    "filtre_itv_expire_bientot": "ITV vence en 30 dias",
    "filtre_itv_expiree": "ITV vencida",
    "filtre_km_moins_30": "< 30 km",
    "filtre_km_30_60": "30 a 60 km",
    "filtre_km_60_120": "60 a 120 km",
    "filtre_km_plus_120": "> 120 km",
    # Kilometrage
    "kilometrage_actuel": "Kilometraje actual",
    "kilometrage_journalier": "Kilometraje del dia",
    "km_unite": "km",
    # Consommation et cout
    "consommation_jour": "Litros del repostaje hoy",
    "litres_plein_label": "Litros del repostaje (L)",
    "cout_plein_label": "Coste del repostaje (EUR)",
    "cout_carburant_jour": "Coste del repostaje hoy",
    # Vehicules
    "vehicules": "Vehiculos",
    "vehicules_titre": "Vehiculos de empresa",
    "liste_vehicules": "Lista de vehiculos",
    "utilisateur": "Usuario",
    "utilisateur_jour": "Usuario del dia",
    "utilisateur_libre": "Libre",
    "modele": "Modelo",
    "matricule": "Matricula",
    "immatriculation": "Matricula",
    "modifier_donnees_jour": "Actualizar datos del dia",
    "journal_quotidien": "Datos del dia",
    "date_jour": "Fecha",
    "utilisateur_label": "Usuario del dia",
    "utilisateur_placeholder": "Nombre del usuario (dejar vacio si libre)",
    "vehicule_sans_photo": "Sin imagen",
    "historique": "Historico",
    "voir_historique": "Ver historico",
    "historique_titre": "Historico del vehiculo",
    "historique_vide": "No hay registros en el historico",
    "historique_aucun_resultat_filtre": "Ningun registro coincide con la busqueda",
    "recherche_historique_utilisateur_placeholder": "Nombre del usuario...",
    "historique_utilisation_titre": "Uso diario",
    "historique_garage_titre": "Envios al taller",
    "immobilisation_en_cours": "En curso",
    "immobilisation_terminee": "Finalizado",
    "filtres": "Filtros",
    "litres_unite": "L",
    "euro_unite": "EUR",
    "vehicules_count": "vehiculo(s) encontrado(s)",
    "mettre_au_garage": "Enviar al taller",
    "remettre_en_service": "Volver al servicio",
    "modal_garage_titre": "Enviar el vehiculo al taller",
    "modal_remise_titre": "Volver a poner el vehiculo en servicio",
    "motif_label": "Motivo",
    "motif_revision": "Revision",
    "motif_panne": "Averia",
    "motif_accident": "Accidente",
    "motif_autre": "Otro",
    "garage_label": "Taller",
    "garage_placeholder": "Nombre del taller",
    "date_debut_immobilisation": "Fecha de inicio",
    "date_retour_estimee": "Fecha estimada de retorno",
    "immobilisation_titre": "Inmovilizacion",
    "voir_immobilisation": "Ver detalles de la inmovilizacion",
    "confirmer": "Confirmar",
    "vehicule_mis_au_garage": "Vehiculo enviado al taller correctamente",
    "vehicule_remis_en_service": "Vehiculo vuelto al servicio correctamente",
    "erreur_immobilisation": "Error al registrar la inmovilizacion",
    "erreur_vehicule_deja_au_garage": "El vehiculo ya esta en el taller",
    "erreur_vehicule_au_garage": "El vehiculo esta en el taller, no se pueden modificar los datos del dia",
    "erreur_vehicule_non_assigne": "Debe utilizar el vehiculo antes de actualizar los datos del dia",
    "erreur_actualisation_non_autorisee": "Solo el usuario del dia o un administrador puede actualizar los datos",
    "erreur_vehicule_deja_occupe": "El vehiculo ya esta en uso",
    "erreur_vehicule_deja_libre": "El vehiculo ya esta libre",
    "erreur_assignation": "Error al asignar el vehiculo",
    "erreur_liberation": "Error al liberar el vehiculo",
    "vehicule_assigne": "Vehiculo asignado correctamente",
    "vehicule_libere": "Vehiculo liberado correctamente",
    "utiliser_ce_vehicule": "Utilizar vehiculo",
    "liberer_ce_vehicule": "Liberar vehiculo",
    "question_utiliser_vehicule": "Desea utilizar este vehiculo?",
    "question_liberer_vehicule": "Desea liberar el vehiculo?",
    "question_remise_en_service": "Desea volver a poner el vehiculo en servicio?",
    "utilisateur_assigne": "Usuario asignado",
    "oui": "Si",
    "non": "No",
    "erreur_vehicule_pas_au_garage": "El vehiculo no esta en el taller",
    "erreur_remise_en_service": "Error al volver a poner el vehiculo en servicio",
    "journal_enregistre": "Datos guardados correctamente",
    "erreur_journal": "Error al guardar los datos",
    "erreur_kilometrage_invalide": "El kilometraje actual no puede ser inferior al ultimo registrado",
    "erreur_carburant_lie": "Los litros y el coste del repostaje deben indicarse juntos.",
    "colonne_date": "Fecha",
    "colonne_utilisateur": "Usuario del dia",
    "colonne_km_jour": "Kilometraje del dia",
    "colonne_litres": "Litros del repostaje",
    "colonne_cout": "Coste del repostaje",
    "colonne_garage": "Taller",
    "colonne_date_fin": "Fecha de retorno",
    "colonne_etat": "Estado",
    "admin_seulement": "Solo administrador",
    # Authentification
    "connexion": "Iniciar sesion",
    "deconnexion": "Cerrar sesion",
    "email": "Identificador",
    "mot_de_passe": "Contrasena",
    "se_connecter": "Iniciar sesion",
    "identifiants_invalides": "Identificador o contrasena incorrectos",
    "identifiant_invalide": "El identificador debe ser un numero de 3 cifras",
    "identifiant_format": "3 cifras, por ejemplo 001",
    "compte_desactive": "Cuenta desactivada. Contacte al administrador",
    "erreur_connexion": "Error al iniciar sesion",
    "admin_utilisateurs": "Gestion de usuarios",
    "admin_utilisateurs_desc": "Crear y administrar cuentas de usuario y administrador",
    "creer_compte": "Crear cuenta",
    "creer_compte_desc": "Indique el identificador, el nombre, la contrasena y el rol del nuevo usuario.",
    "liste_comptes": "Lista de cuentas",
    "nom": "Nombre",
    "prenom": "Nombre",
    "prenom_placeholder": "Ej. Maria",
    "nom_famille": "Apellido",
    "nom_famille_placeholder": "Ej. Garcia",
    "nom_utilisateur": "Nombre",
    "nom_utilisateur_placeholder": "Ej. Maria Garcia",
    "email_placeholder_compte": "001",
    "mot_de_passe_min": "Minimo 3 caracteres",
    "nom_optionnel": "Nombre (opcional)",
    "nom_obligatoire": "El nombre es obligatorio",
    "role": "Rol",
    "role_user": "Usuario",
    "role_admin": "Administrador",
    "compte_actif": "Activo",
    "compte_inactif": "Inactivo",
    "desactiver": "Desactivar",
    "activer": "Activar",
    "supprimer": "Eliminar",
    "confirmer_suppression": "Eliminar esta cuenta?",
    "compte_cree": "Cuenta creada correctamente",
    "statut_modifie": "Estado de la cuenta actualizado",
    "compte_supprime": "Cuenta eliminada",
    "erreur_creation": "Error al crear la cuenta",
    "email_existant": "Este identificador ya esta registrado",
    "auto_modification_interdite": "No puede modificar su propia cuenta",
    "auto_desactivation_interdite": "No puede desactivar su propia cuenta",
    "auto_suppression_interdite": "No puede eliminar su propia cuenta",
    "dernier_admin": "Debe permanecer al menos un administrador activo",
    "introuvable": "Cuenta no encontrada",
    "erreur": "Ha ocurrido un error",
    # Admin vehicules
    "admin_vehicules": "Gestion de vehiculos",
    "admin_vehicules_desc": "Anadir y modificar vehiculos de la flota",
    "ajouter_vehicule": "Anadir vehiculo",
    "modifier_vehicule": "Modificar vehiculo",
    "liste_vehicules_admin": "Lista de vehiculos",
    "photo_vehicule": "Foto",
    "photo_actuelle": "Foto actual",
    "changer_photo": "Nueva foto",
    "photo_aide": "JPG, PNG o WebP. Maximo 5 MB. Sustituye la foto anterior.",
    "vehicule_cree": "Vehiculo creado correctamente",
    "vehicule_modifie": "Vehiculo actualizado correctamente",
    "matricule_existant": "Esta matricula ya existe",
    "vehicule_introuvable": "Vehiculo no encontrado",
    "erreur_creation_vehicule": "Error al crear el vehiculo",
    "erreur_modification_vehicule": "Error al modificar el vehiculo",
    "photo_invalide": "Archivo de imagen no valido",
    "photo_format_invalide": "Formato no permitido (use JPG, PNG o WebP)",
    "photo_trop_volumineuse": "La imagen supera el tamano maximo (5 MB)",
    "erreur_stockage_blob": "Error al guardar la imagen. Contacte al administrador.",
    "aucun_vehicule": "No hay vehiculos registrados",
    "confirmer_suppression_vehicule": "Eliminar este vehiculo y todo su historico?",
    "vehicule_supprime": "Vehiculo eliminado correctamente",
    "erreur_suppression_vehicule": "Error al eliminar el vehiculo",
    # Admin utilisateurs (modification)
    "modifier_compte": "Modificar cuenta",
    "compte_modifie": "Cuenta actualizada correctamente",
    "mot_de_passe_optionnel": "Dejar vacio para mantener la contrasena actual",
    "erreur_modification": "Error al modificar la cuenta",
    # Imprimantes
    "imprimantes": "Impresoras",
    "imprimantes_titre": "Impresoras de empresa",
    "liste_imprimantes": "Lista de impresoras",
    "recherche_imprimantes_placeholder": "Nombre, modelo, ubicacion...",
    "imprimantes_count": "impresora(s) encontrada(s)",
    "localisation": "Ubicacion",
    "compteur_pages": "Contador de paginas",
    "pages_unite": "pag.",
    "dernier_toner": "Ultimo toner",
    "derniere_maintenance": "\u00daltimo mantenimiento",
    "statut_ok": "OK",
    "statut_panne": "Averia",
    "statut_maintenance": "Mantenimiento",
    "enregistrer_evenement": "Registrar evento",
    "nouvel_evenement": "Nuevo evento",
    "date_evenement": "Fecha",
    "type_evenement": "Tipo de evento",
    "evt_compteur": "Actualizacion contador",
    "evt_toner": "Cambio de toner",
    "evt_maintenance": "Mantenimiento en curso",
    "evt_maintenance_terminee": "Mantenimiento finalizado",
    "evt_panne": "Averia",
    "evt_reparation": "Reparacion en curso",
    "commentaire_optionnel": "Comentario (opcional)",
    "commentaire_label": "Comentario",
    "compteur_obligatoire": "Indique el valor del contador",
    "compteur_regressif": "El contador no puede disminuir",
    "evenement_enregistre": "Evento registrado correctamente",
    "erreur_evenement": "Error al registrar el evento",
    "historique_imprimante_titre": "Historico de la impresora",
    "imprimante_introuvable": "Impresora no encontrada",
    "admin_imprimantes": "Gestion de impresoras",
    "admin_imprimantes_desc": "Anadir y administrar impresoras",
    "ajouter_imprimante": "Anadir impresora",
    "modifier_imprimante": "Modificar impresora",
    "modifier": "Modificar",
    "liste_imprimantes_admin": "Lista de impresoras",
    "nom_imprimante": "Nombre / ID",
    "compteur_initial": "Contador inicial",
    "compteur_via_evenements": "modificable solo mediante eventos",
    "statut_deduit_evenements": "Estado calculado segun el ultimo evento",
    "imprimante_creee": "Impresora creada correctamente",
    "imprimante_modifiee": "Impresora actualizada correctamente",
    "imprimante_supprimee": "Impresora eliminada correctamente",
    "nom_existant": "Este nombre ya existe",
    "aucune_imprimante": "No hay impresoras registradas",
    "confirmer_suppression_imprimante": "Eliminar esta impresora y todo su historico?",
    "erreur_creation_imprimante": "Error al crear la impresora",
    "erreur_modification_imprimante": "Error al modificar la impresora",
    "erreur_suppression_imprimante": "Error al eliminar la impresora",
    # Ordinateurs
    "ordinateurs": "Ordenadores",
    "ordinateurs_titre": "Ordenadores de empresa",
    "liste_ordinateurs": "Lista de ordenadores",
    "recherche_ordinateurs_placeholder": "Nombre, marca, usuario, ubicacion...",
    "ordinateurs_count": "ordenador(es) encontrado(s)",
    "nom_ordinateur": "Nombre del equipo",
    "numero_serie": "Numero de serie",
    "marque": "Marca",
    "utilisateur_assigne": "Usuario asignado",
    "non_assigne": "Sin asignar",
    "utilisateur_responsable": "Usuario responsable",
    "systeme_exploitation": "Sistema operativo",
    "processeur": "Procesador",
    "memoire_ram": "Memoria RAM",
    "capacite_stockage": "Almacenamiento",
    "date_acquisition": "Fecha de adquisicion",
    "garantie": "Garantia",
    "garantie_placeholder": "Ej. Hasta 06/2027",
    "statut_en_maintenance": "Mantenimiento",
    "statut_en_panne": "Averia",
    "evt_changement_utilisateur": "Cambio de usuario",
    "evt_entretien": "Mantenimiento",
    "evt_intervention_technique": "Intervencion tecnica",
    "evt_attribution_legacy": "Asignacion a usuario",
    "evt_nettoyage_legacy": "Limpieza",
    "evt_mise_a_niveau_materiel_legacy": "Mejora de hardware",
    "evt_remplacement_piece_legacy": "Sustitucion de pieza",
    "evt_mise_a_jour_legacy": "Actualizacion de configuracion",
    "evt_remise_en_service_legacy": "Puesta en servicio",
    "historique_ordinateur_titre": "Historico del ordenador",
    "ordinateur_introuvable": "Ordenador no encontrado",
    "admin_ordinateurs": "Gestion de ordenadores",
    "admin_ordinateurs_desc": "Anadir y administrar el parque informatico",
    "ajouter_ordinateur": "Anadir ordenador",
    "modifier_ordinateur": "Modificar ordenador",
    "liste_ordinateurs_admin": "Lista de ordenadores",
    "ordinateur_cree": "Ordenador creado correctamente",
    "ordinateur_modifie": "Ordenador actualizado correctamente",
    "ordinateur_supprime": "Ordenador eliminado correctamente",
    "numero_serie_existant": "Este numero de serie ya existe",
    "aucun_ordinateur": "No hay ordenadores registrados",
    "confirmer_suppression_ordinateur": "Eliminar este ordenador y todo su historico?",
    "erreur_creation_ordinateur": "Error al crear el ordenador",
    "erreur_modification_ordinateur": "Error al modificar el ordenador",
    "erreur_suppression_ordinateur": "Error al eliminar el ordenador",
}
